### ISSUE TITLE
Change the dependency on vaadin from v22 to v22-v23

### ISSUE THREAD

**Issue by naoak** [gatanaso/multiselect-combo-box#112]
Hi!

v3.0.0-alpha.1 is currently dependent on vaadin@22. If we change the dependent versions to the range from 22 to 23, it would work fine with also vaadin@23beta. At least it works fine in my use case. How about considering to specify the versions in range?

Thanks.

**Comment by jcgueriaud1** [comment]
The component is working with Vaadin 23, normally pnpm and npm should automatically use the version of the platform.

**Comment by naoak** [comment]
@jcgueriaud1 
Does that mean that the version can be resolved in the user's package.json settings, or should it be handled on the multiselect-combo-box side?

**Comment by jcgueriaud1** [comment]
In short: Normally it's handled by Vaadin, nothing to do on your side or on the component side.

With more details:
If you are using Vaadin 23.x.x the versions of the Vaadin components are overridden to 23.x.x even if the dependency requires version 22.x.x.
If the components are compatible then it will work.
Of course if there are breaking changes, the component won't work. But I think it's not the case between Vaadin 22 and 23.

It's working if you are using the Vaadin platform or Hilla, if you are using only the webcomponents then you have to use pnpm or npm 8.1+ and override the component in your package.json. For example:
```
    "overrides": {
      "@vaadin/component-base": "^23.0.0",
      "@vaadin/vaadin-lumo-styles": "^23.0.0",
      "@vaadin/vaadin-themable-mixin": "^23.0.0",
      ...
    },
```

I tested the component with Vaadin 23 pnpm and npm without issues.

**Comment by naoak** [comment]
@jcgueriaud1 
I didn't know about the overrides feature as I just recently moved to node 16 and npm 8. Thank you very much for the detailed explanation and solution. Very helpful. I will try the overrides property right away.

**Comment by naoak** [comment]
I'm using only the web components. And it worked with the following package.json on npm@8.3.1.
```json
"dependencies": {
  "multiselect-combo-box": "multiselect-combo-box": "^3.0.0-alpha.2",
  "@vaadin/component-base": "^23.0.0",
  "@vaadin/vaadin-lumo-styles": "^23.0.0",
  "@vaadin/vaadin-themable-mixin": "^23.0.0",
  ...,
},
"overrides": {
  "@vaadin/component-base": "$@vaadin/component-base",
  "@vaadin/vaadin-lumo-styles": "$@vaadin/vaadin-lumo-styles",
  "@vaadin/vaadin-themable-mixin": "$@vaadin/vaadin-themable-mixin",
  ...,
},
```
Thanks!

**Comment by danielvanmil** [comment]
Upgrading to 23.0.8 (or later) goes well. When upgrading to 23.1.X (or later?) an error occurs as a non public API is used which is not backwards compatible in the context of #3824 and #3836:

```
multiselect-combo-box.js:481 Uncaught TypeError: this.$.comboBox.$.dropdown._setOverlayWidth is not a function
    at multiselect-combo-box.js:481:1
```
- Is there a plan to upgrade this to 23.1.X (or later?)
- What is the general plan for this component? Is it the same as in @vaadin itself and if so, when will the two be merged etc.?

**Comment by jcgueriaud1** [comment]
A new webcomponent based on this component has been done in Vaadin 23.1 and the Java API is included in 23.2: https://github.com/vaadin/platform/issues/2961
It's not exactly the same.
I don't know if this component will be updated

**Comment by danielvanmil** [comment]
@jcgueriaud1: nice, thanks!
